server:
  port: 18087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.247.160:8848
    sentinel:
      transport:
        dashboard: 120.27.247.160:8080
        port: 8719
  zipkin:
    base-url: http://120.27.247.160:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.66.66
    port: 6379
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall.index: debug
