server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.247.160:8848
    sentinel:
      transport:
        dashboard: 120.27.247.160:8080
        port: 8719
  zipkin:
    base-url: http://120.27.247.160:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_sms?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
feign:
  sentinel:
    enabled: false
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto