server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.247.160:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/usms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search
        - id: index-route  # 同步请求路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
        - id: index-route2  # 异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**

