server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.66:8080
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/usms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search
        - id: index-route  # 同步请求路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
        - id: index-route2  # 异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route  # 异步请求路由
          uri: lb://item-service
          predicates:
            - Path=/*.html
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com, auth.gmall.com
jwt:
  pubFilePath: D:\gmall-rsa\rsa.pub
  cookieName: GMALL-TOKEN


