server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.66:8080
    sentinel:
      transport:
        dashboard: 120.27.247.160:8080
        port: 8719
  zipkin:
    base-url: http://120.27.247.160:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall.item: debug
threadPool:
  corePoolSize: 100
  maximumPoolSize: 500
  keepAliveTime: 60
  blockingQueueSize: 5000
